### ISSUE TITLE
npm package

### ISSUE THREAD

**Issue by Kaixhin** [mil-tokyo/sukiyaki#4]
Rather than using git submodules to manage dependencies, would you consider publishing [npm packages](https://docs.npmjs.com/getting-started/publishing-npm-packages)? That way `npm install sukiyaki` would be the only installation step needed, with [sushi](https://github.com/mil-tokyo/sushi) automatically installed as a dependency (with the version determined by the package.json).

**Comment by milhidaka** [comment]
Thanks for the comment.
I modified some files and uploaded to npm as "milsukiyaki".
https://www.npmjs.com/package/milsukiyaki
